# Generated by Django 5.0 on 2023-12-28 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart_alter_product_options_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'catproduct', 'verbose_name_plural': 'products'},
        ),
    ]
